# Form implementation generated from reading ui file 'weather.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import *
from PyQt6 import *


class Ui_weatherApp(object):
    def setupUi(self, weatherApp):
        weatherApp.setObjectName("weatherApp")
        weatherApp.resize(400, 450)
        weatherApp.setMinimumSize(QtCore.QSize(400, 450))
        weatherApp.setMaximumSize(QtCore.QSize(400, 450))
        font = QtGui.QFont()
        font.setPointSize(48)
        weatherApp.setFont(font)
        weatherApp.setStyleSheet('background-color: rgb(119,195,236); color: white')
        self.centralwidget = QtWidgets.QWidget(parent=weatherApp)
        self.centralwidget.setObjectName("centralwidget")
        self.appTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.appTitle.setGeometry(QtCore.QRect(30, 10, 400, 41))
        self.appTitle.setMinimumSize(QtCore.QSize(400, 0))
        self.appTitle.setMaximumSize(QtCore.QSize(400, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        self.appTitle.setFont(font)
        self.appTitle.setIndent(-1)
        self.appTitle.setObjectName("appTitle")
        self.cityLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.cityLabel.setGeometry(QtCore.QRect(20, 80, 31, 20))
        self.cityLabel.setIndent(0)
        self.cityLabel.setObjectName("cityLabel")
        self.submitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(80, 240, 111, 51))
        self.submitButton.setObjectName("submitButton")
        self.submitButton.setStyleSheet('background-color: rgb(0,110,166)')
        self.fRadioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.fRadioButton.setGeometry(QtCore.QRect(50, 200, 41, 20))
        self.fRadioButton.setChecked(False)
        self.fRadioButton.setStyleSheet('background-color: rgb(0,110,166)')
        self.fRadioButton.setObjectName("fRadioButton")
        self.cRadioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.cRadioButton.setGeometry(QtCore.QRect(170, 200, 41, 20))
        self.cRadioButton.setChecked(False)
        self.cRadioButton.setObjectName("cRadioButton")
        self.cRadioButton.setStyleSheet('background-color: rgb(0,110,166)')
        self.outputLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(10, 310, 381, 91))
        self.outputLabel.setText("")
        self.outputLabel.setVisible(False)
        self.outputLabel.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.outputLabel.setObjectName("outputLabel")
        self.outputLabel.setStyleSheet('background-color: rgb(0,110,166)')
        self.cityInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.cityInput.setGeometry(QtCore.QRect(70, 80, 113, 21))
        self.cityInput.setInputMask("")
        self.cityInput.setText("")
        self.cityInput.setObjectName("cityInput")
        self.cityInput.setStyleSheet('background-color: rgb(0,110,166)')
        self.stateLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.stateLabel.setGeometry(QtCore.QRect(20, 120, 41, 16))
        self.stateLabel.setObjectName("stateLabel")
        self.stateInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.stateInput.setGeometry(QtCore.QRect(70, 120, 113, 21))
        self.stateInput.setObjectName("stateInput")
        self.stateInput.setStyleSheet('background-color: rgb(0,110,166)')
        self.countryLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.countryLabel.setGeometry(QtCore.QRect(10, 160, 61, 20))
        self.countryLabel.setObjectName("countryLabel")
        self.countryInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.countryInput.setGeometry(QtCore.QRect(70, 160, 113, 21))
        self.countryInput.setObjectName("countryInput")
        self.countryInput.setStyleSheet('background-color: rgb(0,110,166)')
        self.imageLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(230, 75, 151, 131))
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        weatherApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=weatherApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 24))
        self.menubar.setObjectName("menubar")
        weatherApp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=weatherApp)
        self.statusbar.setObjectName("statusbar")
        weatherApp.setStatusBar(self.statusbar)

        self.retranslateUi(weatherApp)
        QtCore.QMetaObject.connectSlotsByName(weatherApp)

    def retranslateUi(self, weatherApp):
        _translate = QtCore.QCoreApplication.translate
        weatherApp.setWindowTitle(_translate("weatherApp", "Weather App"))
        self.appTitle.setText(_translate("weatherApp", "Haider\'s Weather App"))
        self.cityLabel.setText(_translate("weatherApp", "<b>City:</b>"))
        self.submitButton.setText(_translate("weatherApp", "Get \n"
                                                           " Temperature"))
        self.fRadioButton.setText(_translate("weatherApp", "F°"))
        self.cRadioButton.setText(_translate("weatherApp", "C°"))
        self.stateLabel.setText(_translate("weatherApp", "State:"))
        self.countryLabel.setText(_translate("weatherApp", "<b>Country:</b>"))

    def displayImage(self, label, path):
        pixmap = QtGui.QPixmap(path)
        pixmap = pixmap.scaled(200, 150, aspectRatioMode=QtCore.Qt.AspectRatioMode.KeepAspectRatio)
        label.setPixmap(QtGui.QPixmap(pixmap))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    weatherApp = QtWidgets.QMainWindow()
    ui = Ui_weatherApp()
    ui.setupUi(weatherApp)
    weatherApp.show()
    sys.exit(app.exec())
